[package]
name = "subxt-metadata"
version = "0.18.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
autotests = false

license = "GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Command line utilities for checking metadata compatibility between nodes."

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
color-eyre = "0.5.11"
frame-metadata = "15.0.0"
hex = "0.4.3"
scale-info = "2.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sp-core = { version = "6.0.0"  }
structopt = "0.3.25"
ureq = { version = "2.2.0", features = ["json"] }
url = { version = "2.2.2", features = ["serde"] }
